= Use Mahjong Soul Logs with akochan-reviewer

== Background (skippable)
Downloading logs from mjsoul is more difficult than from tenhou because it requires a login and the log formats are different.

For a long time, the reviewer had been able to retrieve mjsoul logs via https://github.com/Equim-chan/tensoul[tensoul], a tool I wrote to automate the process of login to mjsoul with an account, download of the logs and convertions to tenhou format. Then the reviewer can retrieve logs in tenhou format by directly using tensoul's API. However, the heroku instance where tensoul is deployed (`\https://tensoul.herokuapp.com`) seems to be banned by mjsoul as the login command keeps getting error code 151. Migrating the instance to another region could mitigate the problem, but I have already done it once. Currently both of the two regions heroku provides are banned and I have no choice.

== Manual
=== Install tempermonkey extenstion on your browser
https://www.tampermonkey.net/[Here]

=== Install `downloadlogs` script
Open https://github.com/vg-mjg/majsoul-plus-mods/raw/main/Utilities/downloadlogs/script.js[this page] on the same browser you installed tempermonkey.

=== Download logs
Login mjsoul, open the log you want to review, then press `S` on the keyboard when the log is loaded.

=== Review
[source,shell]
----
$ akochan-reviewer -i FILENAME -a ACTOR
$ # Example:
$ akochan-reviewer -i log.json -a 2
----
