= Use Mahjong Soul Logs with akochan-reviewer
:experimental:

== Background (skippable)
Downloading logs from mjsoul is more difficult than from tenhou because it requires a login and the log formats are different.

For a long time, the reviewer had been able to retrieve mjsoul logs via https://github.com/Equim-chan/tensoul[tensoul], a tool I wrote to automate the process of login to mjsoul with an account, download of the logs and convertions to tenhou format. I created a dummy account and deployed a tensoul on heroku to provide a more accessible service, then the reviewer could retrieve logs in tenhou format directly by accessing the tensoul instance's API. This was https://github.com/Equim-chan/akochan-reviewer/blob/b815e32e58414361de5b4af5748cabeb6085e9cb/src/download.rs#L5[hard coded] in akochan-reviewer.

However, the heroku instance where tensoul is deployed (`\https://tensoul.herokuapp.com`) seems to be banned by mjsoul recently as the login command keeps getting error code 151. Migrating the instance to another region could mitigate the problem, but I have already done it once. Currently both of the two regions heroku provides are banned and I have no choice.

== Manual
=== Install tempermonkey extenstion on your browser
https://www.tampermonkey.net/[Here]

=== Install `downloadlogs` script
Open https://github.com/vg-mjg/majsoul-plus-mods/raw/main/Utilities/downloadlogs/script.js[this page] on the same browser you installed tempermonkey.

=== Download the log
Login mjsoul, open the log you want to review, then press kbd:[S] after the log is loaded.

=== Review
[source,shell]
----
$ akochan-reviewer -i FILENAME -a ACTOR
$ # Example:
$ akochan-reviewer -i log.json -a 2
----
